# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Heading, text, image & colored buttons.
  icon: "cottage"
  tags:
    - Heading
    - Text
    - Image
    - Buttons

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#ffffff'
  heading:
    heading_text: 
    text_color: '#333232'
    heading_gradient_color: '#A0A2FF'
  subheading:
    text_content:
    text_color: '#333232'
  image:
    image_path: 
    alt_text:
  buttons: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Heading
        subtext:
          - 'Update heading text and color'
  subheading:
    options:
      preview:
        icon: 'description'
  heading_gradient_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
        icon: palette
        icon_color: 
          - key: value
  image:
    options:
      preview:
        icon: 'image'
        text:
          - key: alt_text
          - 'Image'
        subtext:
          - key: image_path
          - 'Update image'
        image:
          - key: image_path
  buttons:
    type: array
    options:
      structures: _structures.buttons