
[module]
hugoVersion.extended = true
hugoVersion.min = '0.161.0'

[[module.mounts]]
source = '.'
target = 'layouts/partials/bookshop'
files = [
  '**/*.hugo.html',
]

[[module.mounts]]
source = '.'
target = 'assets/bookshop'
